### ISSUE TITLE
Build failing: target name -> compile

### ISSUE THREAD

**Issue by theseyi** [nathanhammond/libphonenumber#18] opened 2016-06-29 19:29 UTC
The following line seems to be causing the build script to fail.
Not too familiar with Ant but will investigate, just giving a heads up incase this is something you can quickly amend or provide pointers in the right direction?
`
    <foreach parallel="true" target="compile-country-libphonenumber" param="regioncode" list="${regioncodes}"/>`

**Build Output**
`BUILD FAILED
/build.xml:157: Problem: failed to create task or type foreach
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.`

**Comment by nathanhammond** [comment] 2016-06-30 02:20
You must have additional helpers for `foreach` inside of build.xml to do its thing. These are provided by `ant-contrib`. I'm assuming that is the underlying issue and closing. If not, please feel free to reopen with more information. 😄

**Closed by nathanhammond** 2016-06-30 02:20 UTC

**Comment by theseyi** [comment] 2016-06-30 02:29
Hey @nathanhammond thanks for responding. Yes, I installed `ant-contrib` and created a pull request with the changes I made. The build 'succeeds' with ant-contrib but the issue with the `parallel="true"` parameter still remains, and that target fails. Is there something I'm missing?

**Comment by nathanhammond** [comment] 2016-06-30 02:32
I don't know? I'm far from an expert at `ant` and this works just fine on my box. The code that you see here is what generated the existing dist files on my personal machine. Given that I can't reproduce the problem it's unlikely that I'm going to be able to help you find a solution.

**Comment by theseyi** [comment] 2016-06-30 02:35
Ok, thanks. I do have a workaround in the meantime, but if I come across something more clear cut, I'll let you know. Cheers
